### ISSUE TITLE
Computer never acknowledges defeat

### ISSUE THREAD

**Issue by macthecadillac** [Alfo5123/Connect4#2]
I know this project is a hobby project but this is a major(ish) problem that seriously affects the playability of your implementation. I managed to beat your AI a few times (using a similar AI of my creation) but the program never concedes and keeps the game going even as my AI (with me as the proxy) achieved multiple four-in-a-rows.

**Comment by Alfo5123** [comment]
@macthecadillac thanks so much for pointing it out. By any chance, do you remember how it was the win? Close to any corner or edge? That would be helpful to solve the bug. Thanks

**Comment by Alfo5123** [comment]
@macthecadillac In fact, this is a solved game, that is the first player can always win given that the right moves are played. Thus, indeed winning the AI is certainly possible (and encouraged). However the fact that it doesn't stop after human wins is probably from a bug in detecting the winner. I will solve it. Thanks!

**Comment by Alfo5123** [comment]
It was only one line missing. Fixed it ;) 
Thanks, again

**Comment by macthecadillac** [comment]
No problem. I know it is a solved game but it makes for an interesting target for learning how to make MCTS AI's especially since the game mechanics are so simple. I wonder if there will be a huge performance improvement in python if you used some kind of bit-board instead of a list to store the game state.
